export const colorForFilter = [
    { "id": 1, "color": "White", "code": "#FFFFFF" },
    { "id": 2, "color": "Black", "code": "#000000" },
    { "id": 3, "color": "Gray", "code": "#808080" },
    { "id": 4, "color": "Navy Blue", "code": "#000080" },
    { "id": 5, "color": "Red", "code": "#FF0000" },
    { "id": 6, "color": "Pink", "code": "#FFC0CB" },
    { "id": 7, "color": "Blue", "code": "#0000FF" },
    { "id": 8, "color": "Green", "code": "#008000" },
    { "id": 9, "color": "Yellow", "code": "#FFFF00" },
    { "id": 10, "color": "Purple", "code": "#800080" },
    { "id": 11, "color": "Brown", "code": "#A52A2A" },
    { "id": 12, "color": "Orange", "code": "#FFA500" },
    { "id": 13, "color": "Beige", "code": "#F5F5DC" },
    { "id": 14, "color": "Cream", "code": "#FFFDD0" },
    { "id": 15, "color": "Ivory", "code": "#FFFFF0" },
    { "id": 16, "color": "Tan", "code": "#D2B48C" },
    { "id": 17, "color": "Maroon", "code": "#800000" },
    { "id": 18, "color": "Teal", "code": "#008080" },
    { "id": 19, "color": "Charcoal", "code": "#36454F" },
    { "id": 20, "color": "Olive Green", "code": "#556B2F" },
    { "id": 21, "color": "Peach", "code": "#FFDAB9" },
    { "id": 22, "color": "Turquoise", "code": "#40E0D0" },
    { "id": 23, "color": "Magenta", "code": "#FF00FF" },
    { "id": 24, "color": "Lavender", "code": "#E6E6FA" },
    { "id": 25, "color": "Sky Blue", "code": "#87CEEB" },
    { "id": 26, "color": "Mint Green", "code": "#98FF98" },
    { "id": 27, "color": "Coral", "code": "#FF7F50" },
    { "id": 28, "color": "Royal Blue", "code": "#4169E1" },
    { "id": 29, "color": "Salmon", "code": "#FA8072" },
    { "id": 30, "color": "Lilac", "code": "#C8A2C8" },
    { "id": 31, "color": "Burgundy", "code": "#800020" },
    { "id": 32, "color": "Mustard Yellow", "code": "#FFDB58" },
    { "id": 33, "color": "Indigo", "code": "#4B0082" },
    { "id": 34, "color": "Khaki", "code": "#F0E68C" },
    { "id": 35, "color": "Aqua", "code": "#00FFFF" },
    { "id": 36, "color": "Slate", "code": "#708090" },
    { "id": 37, "color": "Ruby", "code": "#E0115F" },
    { "id": 38, "color": "Orchid", "code": "#DA70D6" },
    { "id": 39, "color": "Taupe", "code": "#483C32" },
    { "id": 40, "color": "Copper", "code": "#B87333" },
    { "id": 41, "color": "Gold", "code": "#FFD700" },
    { "id": 42, "color": "Silver", "code": "#C0C0C0" },
    { "id": 43, "color": "Bronze", "code": "#CD7F32" },
    { "id": 44, "color": "Rust", "code": "#B7410E" },
    { "id": 45, "color": "Emerald Green", "code": "#50C878" },
    { "id": 46, "color": "Plum", "code": "#8E4585" },
    { "id": 47, "color": "Cobalt Blue", "code": "#0047AB" },
    { "id": 48, "color": "Mahogany", "code": "#C04000" },
    { "id": 49, "color": "Mauve", "code": "#E0B0FF" },
    { "id": 50, "color": "Olive Drab", "code": "#6B8E23" }
]

export const ratingsFilter=[
    {id:1,rating:'4'},
    {id:2,rating:'3'},
]
export const Discount=[
    {id:1,discount:'10'},
    {id:2,discount:'20'},
    {id:3,discount:'30'},
    {id:4,discount:'40'},
    {id:5,discount:'50'},
    {id:6,discount:'60'},
    {id:7,discount:'70'},
    {id:8,discount:'80'},
    {id:9,discount:'90'}
]